
package gui;

import java.awt.BorderLayout;
import javax.swing.JPanel;
/**
 *
 * @author Katherine Nussbaum
 */
public class jfrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfrmMenuPrincipal
     */
    public jfrmMenuPrincipal() {
        initComponents();
        // ventana maximizada
        setExtendedState(jfrmMenuPrincipal.MAXIMIZED_BOTH);
        // Quitar botones de manejo de ventana
        setUndecorated(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        btnVentas = new javax.swing.JMenu();
        btnRegistros = new javax.swing.JMenu();
        btnAdministrcion = new javax.swing.JMenu();
        btnIngresoEjecutivo = new javax.swing.JMenuItem();
        btnAyuda = new javax.swing.JMenu();
        btnCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 248, 248));
        setType(java.awt.Window.Type.POPUP);

        jPanelPrincipal.setBackground(new java.awt.Color(248, 248, 248));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JAVACars", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 0, 24), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanelPrincipal.setName(""); // NOI18N

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        btnVentas.setText("Ventas");
        jMenuBarPrincipal.add(btnVentas);

        btnRegistros.setText("Registros");
        jMenuBarPrincipal.add(btnRegistros);

        btnAdministrcion.setText("Administración");

        btnIngresoEjecutivo.setText("Ingreso Ejecutivo");
        btnIngresoEjecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoEjecutivoActionPerformed(evt);
            }
        });
        btnAdministrcion.add(btnIngresoEjecutivo);

        jMenuBarPrincipal.add(btnAdministrcion);

        btnAyuda.setText("Ayuda");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        btnAyuda.add(btnCerrar);

        jMenuBarPrincipal.add(btnAyuda);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // salir de la aplicación
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnIngresoEjecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoEjecutivoActionPerformed
        jPanelIngresoEjecutivo ingresoEjecutivo = new jPanelIngresoEjecutivo();
        cambioPanel(ingresoEjecutivo);
    }//GEN-LAST:event_btnIngresoEjecutivoActionPerformed

    public void cambioPanel(JPanel panel){
        jPanelPrincipal.removeAll();
        jPanelPrincipal.setSize(700, 500);
        jPanelPrincipal.setLayout(new BorderLayout());
        jPanelPrincipal.add(panel, BorderLayout.CENTER);
        jPanelPrincipal.revalidate();
        jPanelPrincipal.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAdministrcion;
    private javax.swing.JMenu btnAyuda;
    private javax.swing.JMenuItem btnCerrar;
    private javax.swing.JMenuItem btnIngresoEjecutivo;
    private javax.swing.JMenu btnRegistros;
    private javax.swing.JMenu btnVentas;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
